name: Jacoco Report

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run unit tests
        run: ./gradlew build test

      - name: Install Android Emulator dependencies
        run: sudo apt-get install -yq libgl1-mesa-dev qemu-kvm

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-snapshot-load"

      - name: Wait for Android Emulator to fully boot
        run: |
          adb wait-for-device shell getprop sys.boot_completed | grep -m 1 '1'
          sleep 30  # Extra wait time to ensure the emulator is ready

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest

      - name: Generate combined Jacoco report
        run: ./gradlew JacocoDebugCodeCoverage

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/JacocoDebugCodeCoverage/html
